### ISSUE TITLE
Problem with String and ByteString in NodeID (or reference to parent string NodeId).

### ISSUE THREAD

**Issue by xydan83** [open62541/open62541-nodeset-loader#231]
Hi!
I found a problem with String and ByteString in Node ID when I was trying to import a simple xml.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<UANodeSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd">
    <NamespaceUris>
        <Uri>urn:rozhkov-nb:UnifiedAutomation:UaServerCpp</Uri>
        <Uri>http://www.unifiedautomation.com/DemoServer/</Uri>
    </NamespaceUris>
    <Aliases>
        <Alias Alias="HasTypeDefinition">i=40</Alias>
        <Alias Alias="Organizes">i=35</Alias>
        <Alias Alias="UInt32">i=7</Alias>
    </Aliases>
    <UAObject NodeId="ns=2;s=Demo.Static" BrowseName="2:Static" ParentNodeId="i=85">
        <DisplayName>000_Static</DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">i=61</Reference>
            <Reference ReferenceType="Organizes">ns=2;i=4294967294</Reference>
            <Reference ReferenceType="Organizes" IsForward="false">i=85</Reference>
        </References>
    </UAObject>
    <UAVariable NodeId="ns=2;i=4294967294" BrowseName="2:VariableWithNumericNodeId" ParentNodeId="ns=2;s=Demo.Static" DataType="UInt32" AccessLevel="3" UserAccessLevel="3">
        <DisplayName>VariableWithNumericNodeId</DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
            <Reference ReferenceType="Organizes" IsForward="false">ns=2;s=Demo.Static</Reference>
        </References>
    </UAVariable>
</UANodeSet>
```

An error message appears during the import process.
![image](https://github.com/open62541/open62541-nodeset-loader/assets/86729310/2d22df1e-494d-4480-842a-0c14397dbcdf)

The trace tells us that the problem may be related to an attempt to remove some node container.
![image](https://github.com/open62541/open62541-nodeset-loader/assets/86729310/832789bc-acfa-411a-9d0d-ef2fd087dd76)

When I replace String Node ID with Index everything is fine. The import completes successfully.
By the way, ByteString has the same problem...

**Comment by xydan83** [comment]
I think the problem might be in the string reference with the second Node.

![image](https://github.com/open62541/open62541-nodeset-loader/assets/86729310/010b91ba-5860-480c-aad8-789b6d3dedd8)

**Comment by paddor** [comment]
Possibly related to https://github.com/open62541/open62541/issues/5794 ?

**Comment by matkonnerth** [comment]
looks like this issue is related to: https://github.com/open62541/open62541/issues/5794

**Comment by xydan83** [comment]
Yes, it seems. But I can't find anything in the standard about the mandatory order of nodes in xml.

**Comment by matkonnerth** [comment]
there is no required order in the xml, this is definitive a bug within the nodesetloader

**Comment by xydan83** [comment]
![image](https://github.com/open62541/open62541-nodeset-loader/assets/86729310/be15c3a3-d27c-423c-9505-cfa1623344ac)

Very strange. How it possibly?


![image](https://github.com/open62541/open62541-nodeset-loader/assets/86729310/64761874-2573-4e05-909e-b57bf340cf61)

**Comment by matkonnerth** [comment]
no deep copy of String copy was made in sort.c, here is the fix https://github.com/open62541/open62541-nodeset-loader/pull/232/commits
