### ISSUE TITLE
The default value of ATTRIBUTE_VALUERANK is -2 (any). But in the standard: -1 (scalar).

### ISSUE THREAD

**Issue by xydan83** [open62541/open62541-nodeset-loader#234]
Hi again.
I noticed in Nodeset.c some possible inaccuracies in the attributes, in the default values.

![image](https://github.com/open62541/open62541-nodeset-loader/assets/86729310/04904e87-9fba-46d1-8ae8-2db9e9fc8ef0)

I'm not sure, but in standart wrote: _The value rank. If not specified, the default value is -1 (Scalar)._

https://reference.opcfoundation.org/v104/Core/docs/Part6/F.8/

Can this be fixed?

**Comment by matkonnerth** [comment]
Hi, for sure, don't hesitate to propose a PR.
